### PR TITLE
Set font fallback on Arial for unsupported locales, prevent the fallb…

### PR DESCRIPTION
**Pull request by TheoChevalier**
…ack font to be bold

'Arial' was here for a reason :)

### CODE REVIEW

**Comment by flodolo** [comment]
I confess that I'm starting to be a bit concerned about how many fonts we're loading (we're approaching 1 MB), and if we should go back to use a smaller set of fonts.

**Comment by TheoChevalier** [comment]
> I confess that I'm starting to be a bit concerned about how many fonts we're loading (we're approaching 1 MB), and if we should go back to use a smaller set of fonts.

I’m not adding a new one, just reusing it with a different name

**Comment by flodolo** [comment]
Completely missed that.

**Comment by flodolo** [comment]
Tested and everything looks good, thanks.

**Pull request merged**
