### PR TITLE
Clean up public urls

### LINKED ISSUE #583: Clean up available URLs
While looking at the functional tests for pages, I noticed some strange URLs in the app
* `changelog.php`: I assume it was maintained for retro-compatibility, but I don't think we should keep it (checking access.log on the prod server could confirm that)
* `repocomparizon`, `repocomparison`: empty page
* `channelcomparizon`: we should keep only `channelcomparison`

Also note that most of these views generate warnings in the log.

### PR DESCRIPTION
**Pull request by SkySymbol**
Fix #583, removing unnecessary urls.

### CODE REVIEW

**Comment by TheoChevalier** [comment]
Looks like you need to update the functional tests and remove /channelcomparizon/ :)
(And you already know where it is :p)

**Comment by SkySymbol** [comment]
Right, my bad

**Comment by TheoChevalier** [comment]
Thank you @SkySymbol ! :beers: 
If @flodolo has no comment, it looks good to me

**Comment by flodolo** [comment]
It looks good, thanks.

**Pull request merged**
