### PR TITLE
Issue #577 – Transition from woff to woff2 fonts

### PR DESCRIPTION
**Pull request by clement-lefevre**
In issue #577 it was required to move from woff to woff2 for fonts files.

It was suggested to convert the files, however I found some downloadable versions that proved to be lighter than converted versions and then checked on specific locales like ro, fu and so on and saw everything.

So it seems that those one are corrects. I can take care of providing converted versions at any time if some error are discovered at any time.

### CODE REVIEW

**Comment by TheoChevalier** [comment]
Please keep woff fonts for compatibility with browsers not yet supporting woff2 
Example: https://github.com/mozfr/nightly/blob/master/web/assets/style/base.css#L2

**Comment by flodolo** [comment]
(which is [a lot of browsers](http://caniuse.com/#feat=woff2)...

**Comment by TheoChevalier** [comment]
(both woff and woff2 files are missing in the commit)

**Comment by TheoChevalier** [comment]
wondering if woff2 only loads with HTTPS

**Comment by clement-lefevre** [comment]
Seems better when src: is not overwritten and redefined.
woff2 fonts are now correctly downloaded.

**Comment by TheoChevalier** [comment]
lgtm now

**Pull request merged**
