### PR TITLE
(fixes issue #897) Use Zilla font in Transvision

### PR DESCRIPTION
**Pull request by flodolo**
fixes issue #897

### CODE REVIEW

**Comment by flodolo** [comment]
Black Zilla Highlight (don't like it very much)

schermata 2017-11-07 alle 18 05 47

**Comment by flodolo** [comment]
Black highlight, white fill for the text

schermata 2017-11-07 alle 18 11 10

**Comment by TheoChevalier** [comment]
Thanks for doing that, @flodolo! I think the latest version looks great, happy to ship that one if it works for you as well.
Also I can’t help but notice the mozilla logo is not *exacly* how it’s supposed to be (paddings are a bit off), do you want me to ask the designers in my team if they would accept to help us here?

**Comment by flodolo** [comment]
> Also I can’t help but notice the mozilla logo is not exacly how it’s supposed to be (paddings are a bit off), do you want me to ask the designers in my team if they would accept to help us here?

The fun thing is that the padding is produced by the Zilla Slab Highlight font. I could do it manually, if you mean distributing the padding evenly around the text.

**Comment by flodolo** [comment]
> do you want me to ask the designers in my team if they would accept to help us here

If they can, go for it. We only have the SVG file though.

**Comment by flodolo** [comment]
Using Zilla and manually placing highlights around text

schermata 2017-11-08 alle 17 08 01

**Comment by flodolo** [comment]
Interesting: the font is bold 46pt, and yet it's completely different between Zilla (heavier) and Zill Highlight.

**Comment by TheoChevalier** [comment]
Thanks, it looks really nice! No need to bother the designers, then.
Just noticed we’re not using `$cache_bust` on the logo URL, do you think we should, or the default value for svg is already short enough?

**Comment by flodolo** [comment]
> Just noticed we’re not using $cache_bust on the logo URL, do you think we should, or the default value for svg is already short enough?

Default is one month. Let me squash and add it.

**Pull request merged**
