### PR TITLE
(fix #905) New QA view: keyboard shortcuts

### LINKED ISSUE #905: Add QA view for keyboard shortcuts
Sorely needed, especially after shipping 3 locales with broken shortcut to exit Firefox on macOS (and another handful fixed by myself.)

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by flodolo** [comment]
Note: can you tell me if any of those showing up in French are false positive?

**Comment by TheoChevalier** [comment]
I suspect shortcuts for Chatzilla and Editor to be potential false positives, but I’m pretty sure the others are actual errors (really nice work to expose those!)

**Comment by flodolo** [comment]
I'll take another look at those tomorrow, and see if I can spot more false positive.

**Comment by flodolo** [comment]
Ugh, completely excluding Chatzilla.
https://hg.mozilla.org/chatzilla/file/default/locales/en-US/chrome/chatzilla.properties#l64

**Pull request merged**
