### PR TITLE
 Improve check variables controls, switch to MVC

### PR DESCRIPTION
**Pull request by flodolo**
* We need l10njs checks also in browser (for PDFViewer and Loop)
* l10njs: _ is a valid character for a variable name
* l10njs: ignore white spaces ({{n}} == {{ n }})
* printf: discovered that %s is not the same as %S: https://bugzilla.mozilla.org/show_bug.cgi?id=1133554
* Use regular expression to check translations. Example: en-US has "$name", translation has "$nameDA", error is not reported with strpos.

Switched view to MVC and added component filter to view.

### CODE REVIEW

**Comment by flodolo** [comment]
This fixes #337, which is not really an easy pick.

**Comment by flodolo** [comment]
Using this PR to switch to MCV too, so WIP for now (we need a tag for that).

**Comment by flodolo** [comment]
This is really weird. I pushed several times to my branch, but it's not reflected in this PR :8ball:

**Comment by flodolo** [comment]
Got a reply from Github support (that was fast, especially on Easter morning!). It's an issue on their side, they're working on it.

**Comment by flodolo** [comment]
OK, PR updated, ready to test and review.

**Comment by pascalchevrel** [comment]
Works well, LGTM

**Pull request merged**
