### PR TITLE
Update logo with new Mozilla style

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by flodolo** [comment]
Per IRC discussion: we might want to revise this when the font is available, but this should be a decent start.

**Comment by TheoChevalier** [comment]
Thanks! 🎉  However we probably don’t want full-white background on the PNGs?

**Comment by flodolo** [comment]
Yeah, I fixed it. No idea why the SVG/PNG export adds background (I manually fixed the SVG in editor, for the PNG had to use another software to export)

**Comment by flodolo** [comment]
Optimized PNGs with pngcrush too.

**Pull request merged**
