### PR TITLE
Full hi-DPI support

### PR DESCRIPTION
**Pull request by TheoChevalier**
Couldn’t resist, those blurry assets were hurting my eyes :)

Before the patch on retina display:
capture d ecran 2016-08-01 a 16 35 48

After the patch on retina display:
capture d ecran 2016-08-01 a 16 35 15

The new menu button is slightly bigger (reused the current one on mozilla.org), but that should be the only change noticeable with a non hi-DPI screen.

### CODE REVIEW

**Comment by TheoChevalier** [comment]
Oh, and also less resources to load for everybody \o/

**Comment by TheoChevalier** [comment]
I’m torn on the color of “menu”. Maybe more like this to match the logo?

capture d ecran 2016-08-01 a 18 27 07

**Comment by flodolo** [comment]
Yes, same color looks like a good idea.

**Comment by flodolo** [comment]
Everything looks fine, but I also confess I don't have a high-DPI screen to check if something looks funny. Feel free to merge if you don't have anything else to add.

**Comment by TheoChevalier** [comment]
> Everything looks fine, but I also confess I don't have a high-DPI screen to check if something looks funny. Feel free to merge if you don't have anything else to add.

Thanks. Looks like Travis has troubles to clone/download things, will check back later ;)

**Pull request merged**
