### PR TITLE
Update edit links (remove Pootle, support FxiOS and mozilla.org)

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by TheoChevalier** [comment]
Tested a bit around, seem to work pretty well!

Just found a case where it doesn’t work, not sure if it’s because of the link or a Pontoon bug.
I’ve tried with an Arabic string containing markup and variable:

http://localhost:8082/?recherche=test&repo=mozilla_org&sourcelocale=en-US&locale=ar&search_type=strings#mozilla_org_firefox_desktop_fast.lang_6b816f4e → links to https://pontoon.mozilla.org/ar/mozillaorg/firefox/desktop/fast.lang/?search=%D8%AA%D9%81%D9%88%D9%82%20%D9%81%D9%8E%D9%8A%D9%8E%D8%B1%D9%81%D9%8F%D9%83%D8%B3%20%D8%B9%D9%84%D9%89%20%D8%A8%D8%A7%D9%82%D9%8A%20%D8%A7%D9%84%D9%85%D9%8F%D8%AA%D8%B5%D9%81%D8%AD%D8%A7%D8%AA%20%D9%81%D9%8A%20%D8%A7%D8%AE%D8%AA%D8%A8%D8%A7%D8%B1%20%D8%A3%D8%AF%D8%A7%D8%A1%20%D9%85%D9%8F%D8%B3%D8%AA%D9%82%D9%84%20%D9%88%D8%AD%D8%B5%D9%84%20%D8%B9%D9%84%D9%89%20%D8%A5%D8%AB%D8%B1%D9%87%20%D8%B9%D9%84%D9%89%20%D9%84%D9%82%D8%A8%20%3Cbr%20class=%22wide-br%22%3E%3Ca%20href=%22%(url1)s%22%20data-interaction=%22outbound%20link%22%3E%22%D9%85%D9%84%D9%83%20%D8%A7%D9%84%D8%B3%D8%B1%D8%B9%D8%A9%22%3C/a%3E which goes infinite loading here.

**Comment by flodolo** [comment]
Not sure if @mathjazz has ideas.

This works
https://pontoon.mozilla.org/ar/mozillaorg/firefox/desktop/fast.lang?search=%D8%AA%D9%81%D9%88%D9%82%20%D9%81%D9%8E%D9%8A%D9%8E%D8%B1%D9%81%D9%8F%D9%83%D8%B3%20%D8%B9%D9%84%D9%89%20%D8%A8%D8%A7%D9%82%D9%8A%20%D8%A7%D9%84%D9%85%D9%8F%D8%AA%D8%B5%D9%81%D8%AD%D8%A7%D8%AA%20%D9%81%D9%8A%20%D8%A7%D8%AE%D8%AA%D8%A8%D8%A7%D8%B1%20%D8%A3%D8%AF%D8%A7%D8%A1%20%D9%85%D9%8F%D8%B3%D8%AA%D9%82%D9%84%20%D9%88%D8%AD%D8%B5%D9%84%20%D8%B9%D9%84%D9%89%20%D8%A5%D8%AB%D8%B1%D9%87%20%D8%B9%D9%84%D9%89%20%D9%84%D9%82%D8%A8%20%3Cbr%20class=%22wide-br%22%3E%3Ca%20

As soon as I add the %(url1)s it doesn't. Even this creates a loop
https://pontoon.mozilla.org/ar/mozillaorg/firefox/desktop/fast.lang?search=%(test)s

**Comment by mathjazz** [comment]
URI components need to be [encoded](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent).

So:
- `%(url)s`-> `%25(url)s`
- `%(test)s`-> `%25(test)s`

Pontoon breaks, because it tries to `decodeURIComponent("%")` and `%` isn't [encodedURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent). Filing a bug.

**Comment by mathjazz** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1396080

**Comment by TheoChevalier** [comment]
Thanks both!
@flodolo, I will let you decide if you want to merge it now because of Pootle shutdown, or want to wait for bug 1396080. Either are fine by me, I can deploy it once it’s merged

**Comment by flodolo** [comment]
> @flodolo, I will let you decide if you want to merge it now because of Pootle shutdown, or want to wait for bug 1396080. Either are fine by me, I can deploy it once it’s merged

Actually, we had fix to stuff on our side too (we were not encoding the text). Fixed in https://github.com/mozfr/transvision/pull/878/commits/f603ef224ec6103de1550a2619f720c93898e67e

Also cutting the text at 250 character, no sense in sending over a poem…

**Comment by TheoChevalier** [comment]
Not sure if we want to do something for empty/missing strings in mozilla.org, but if not we should probably hide the link instead of searching for `@@missing@@`

**Comment by flodolo** [comment]
> Not sure if we want to do something for empty/missing strings in mozilla.org, but if not we should probably hide the link instead of searching for @@missing@@

Good point. Fixed.

**Comment by flodolo** [comment]
Ugh, why are we even altering the target text? :-\

**Comment by flodolo** [comment]
We should really refactor and centralize the code used to display results.

**Pull request merged**
