### PR TITLE
Adding prestissimo as a dev dependency

### PR DESCRIPTION
**Pull request by MatonAnthony**
Do not merge.
It's just to have the travis run to compare performance.

### CODE REVIEW

**Comment by MatonAnthony** [comment]
Travis build took 134 sec with prestissimo.

**Comment by MatonAnthony** [comment]
Travis took 121 secon that build : https://travis-ci.org/mozfr/transvision/jobs/109031892
Using the default suggested configuration.

**Comment by MatonAnthony** [comment]
It took 108 seconds with the last build : https://travis-ci.org/mozfr/transvision/jobs/109032440
I suggest we keep that. It implies to ask Travis to make 12 parallels request.

**Comment by MatonAnthony** [comment]
@pascalchevrel What do you think about it ?

**Comment by pascalchevrel** [comment]
I think it's fine but the dependency should be in the require-dev section of composer.json, not the require one, because we want to do that to speed up our dev environment but don't want to install that dependency on production.

**Comment by MatonAnthony** [comment]
I think it's good this time.

**Comment by pascalchevrel** [comment]
I am stull seeing it in the require section and not require-dev ;)

**Comment by MatonAnthony** [comment]
Are you sure, you unfold the code ?
That what i'm seeing : 
capture d ecran 2016-02-19 a 14 52 01

**Comment by pascalchevrel** [comment]
you're right, merging, thanks! :+1:

**Pull request merged**
